site_name: xConnect Documentation
site_url: http://docs.senecaxconnect.com
site_description: xConnect Documentation
site_author: Seneca

repo_name: 'senecaxconnect/xconnect_docs'
repo_url: 'https://github.com/senecaxconnect/xconnect_docs'

nav:
    - Platform:
       - Overview: Platform_Overview.md
       - Server Agent: Agent_Overview.md
       - Gateway: Gateway_Overview.md
       - Web Dashboard: Dashboard_Overview.md
    - Getting Started:
       - Quick Start Guide: Getting_Started.md
       - Step 1 - Gateway Setup:
         - Turnkey: Gateway_TurnKey.md
         - Docker: Gateway_Docker.md
       - Step 2 - Install Agent: Agent_Install.md
       - Step 3 - Web Dashboard: Dashboard_Setup.md
    - User Guide:
        - Dashboards: Usage_Dashboards.md
        - Bookmarks: Usage_Bookmarks.md
        - User Types: Usage_Roles.md
        - Management:
            - Customers: Usage_ManageCustomers.md
            - Users: Usage_ManageUsers.md
            - Gateways: Usage_ManageGateways.md
            - Devices: Usage_ManageDevices.md
            - Event Configurations: Usage_ManageEventConfigurations.md
            - Email Profiles: Usage_ManageEmailProfiles.md
            - Remote Commands: Usage_ManageRemoteCommands.md
            - 3rd Party Connectors: Usage_ManageConnectors.md
        - Event Logs: Usage_EventLogs.md
    - Additional Documentation:
       - Data Flow: Data_Flow.md
       - Cyber-Security: Cyber_Security.md
    - Support: Support.md

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  logo: 'images/logo.svg'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2020 <a href="https://www.senecadata.com"> - Seneca Data Distributors, Inc</a>
