site_name: xConnect Documentation Library
nav:
    - Platform:
       - Overview: Overview.md
       - Server Agent: Agent.md
       - Gateway: Gateway.md
       - Web Dashboard: Dashboard.md
    - Installation:
       - Getting Started: Getting_Started.md
       - Step 1 - Gateway Setup:
         - Turnkey: Gateway_TurnKey.md
         - Docker: Gateway_Docker.md
       - Step 2 - Install Agent: Agent_Install.md
       - Step 3 - Web Dashboard: Dashboard_Setup.md
    - Additional Documentation:
       - Data Flow: Data_Flow.md
       - Cyber-Security: Cyber_Security.md
    - Support: Support.md
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'cyan'
  logo: 'images/logo.svg'
